spring:
  application:
    name: kafka-producer
  datasource:
    url: jdbc:postgresql://localhost:5432/base_kafka?createDatabaseIfNotExist=true&useSSL=false
    username: guiborges
    password: root
  jpa:
    show-sql: true
server:
  port: 9001
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer